#!/bin/bash

module purge
source $HOME/.env_bas


# Environnement Cray de base
#module load cce/20.0

# Architecture CPU + GPU
#module load craype-accel-amd-gfx90a craype-x86-trento

# Compilateur
#module load PrgEnv-cray #amd/8.6.0


# ROCm/HIP
#module load rocm/7.2.0
#module load rocm/6.4.3


#ln -sf $ROCM_PATH/lib/libamdhip64.so libamdhip64.so.6
#export LD_LIBRARY_PATH=${PWD}:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=$ROCM_PATH/lib:$LD_LIBRARY_PATH

which amdclang

module list

# Basilisk compilation
BASILISK=/lus/home/CT1/c1916930/hjacquet/work/basilisk/src
cd $BASILISK
ln -s config.gcc config
make > logs.make

cd $BASILISK/grid/gpu
make liberrors.a > logs.make

cd ../hip
make > logs.make
