#!/bin/bash

module purge

# Version de l'environnement Cray
#module load cpe/25.09
#module load cpe/23.12

# Architecture cible : MI250X (gfx90a) + CPU Trento
#module load craype-accel-amd-gfx90a craype-x86-trento # MI250X GPU
module load craype-accel-amd-gfx942 # MI300A APU

# Compilateur Cray (supporte OpenACC → AMD GPU)
#module load PrgEnv-cray
#module load PrgEnv-amd

module load rocm/7.2.0

export BASILISK=/lus/home/CT2B/cad16450/atsetoglou/basilisk/src
